#!/usr/bin/env python3

"""CUPS Backend for PrintNode"""

# Based on https://www.cups.org/doc/api-filter.html
# Based on https://github.com/PrintNode/PrintNode-Python
# Based on https://www.printnode.com/en/docs/api/curl#printjob-creating

# Version history:
# 1.0    17.09.2019  gw  Inital version
# 1.1    21.01.2020  gw  Added CUPS JobID as Jobtitle
# 1.2    20.02.2020  gw  Added support for Duplex
# 1.3    04.06.2020  gw  Added check for A5 paper
# 1.4    05.06.2020  gw  Changed config to yaml and added mutli account
# 1.5    10.06.2020  gw  Add support for raw Print
# 1.5.1  15.07.2020  gw  Prevent printNode.yml from being sorted alphabeticly
# 1.6    22.07.2020  gw  Added handling for A5_Overrides
# 1.6.1  27.07.2020  gw  Changed A5_Overrides to be printer specific
# 1.7    24.08.2020  gw  Added A5 and global override option duplex
# 1.8    12.02.2021  gw  Added color override Option and allowed overrides to be queue specific
# 1.8.1  12.04.2021  gw  Fixed bug when adding new printer ID to printnode.yml
# 1.9    10.10.2022  gw  Allow Printer specific A5_Printer overrides (BEE-33584)
# 1.10   11.10.2022  gw  Fixed bug where A5_Printer override_options were ignored (BEE-33584)

import base64
import logging
import os
import sys
import yaml
from printnodeapi import Gateway

QUEUE = os.environ.get("PRINTER")
PRINTER_ID = ""
API_KEY = ""
LOGFILE_PATH = "/var/log/cups/printnode_log"
PRINTNODE_CONFIG_PATH = "/etc/cups/printNode.yml"
JOBTITLE = sys.argv[1]
WRITE_CONFIG = False
PRINTNODE_GW = None
DEBUG_LEVEL_SWITCHER = {
    "debug": 10,
    "info": 20,
    "warning": 30,
    "error": 40,
    "critical": 50
}

# Override Vairables
IS_A5 = False
A5_PRINTER = ''
A5_PRINTER_OVERRIDE_OPTIONS = {}
GLOBAL_PRINTER_OVERRIDES = {}

def set_a5_options(overrides):
    """ Force A5 settings """
    PRINTNODE_OPTIONS.update(overrides)
    PRINTNODE_OPTIONS["paper"] = "A5"
    logging.info("Setting A5 Overrides: %s", overrides)

def get_overrides(ID, OVERRIDE_OPTIONS):
    GLOBAL_PRINTER_OVERRIDES.clear()
    A5_PRINTER_OVERRIDE_OPTIONS.clear()
    for PRINTER_OVERRIDES in OVERRIDE_OPTIONS:
        if (PRINTER_OVERRIDES.get("Printer_ID", "") == ID or
                PRINTER_OVERRIDES.get("Queue", "") == QUEUE):
            for KEY, VAL in PRINTER_OVERRIDES.items():
                if KEY == "Duplex":
                    GLOBAL_PRINTER_OVERRIDES["duplex"] = VAL
                elif KEY == "Color":
                    GLOBAL_PRINTER_OVERRIDES["color"] = VAL
                elif KEY == "A5_Bin":
                    A5_PRINTER_OVERRIDE_OPTIONS["bin"] = VAL
                elif KEY == "A5_Rotation":
                    A5_PRINTER_OVERRIDE_OPTIONS["rotate"] = VAL
                elif KEY == "A5_Duplex":
                    A5_PRINTER_OVERRIDE_OPTIONS["duplex"] = VAL
                elif KEY == "A5_Printer":
                    return VAL
                elif KEY in ("Printer_ID", "Queue"):
                    continue
                else:
                    logging.warning("%s is not a valid override options", KEY)

# Check if ID is a valid Int
PRINTER_URI = os.environ['DEVICE_URI']
try:
    PRINTER_ID = int(PRINTER_URI[12:])
except ValueError:
    sys.stderr.write("CRIT: Could not determine Printer ID. "
                     "Ensure that the printers adress is a printNode ID")
    sys.exit(1)

# Parse printNode.yml config
try:
    with open("%s" % PRINTNODE_CONFIG_PATH, "r") as PRINTNODE_CONFIG_FILE:
        PRINTNODE_CONFIG = yaml.safe_load(PRINTNODE_CONFIG_FILE)
except yaml.YAMLError as ex:
    sys.stderr.write("CRIT: Could not parse yaml config file: %s" % (PRINTNODE_CONFIG_PATH))
    sys.exit(2)
except IOError:
    sys.stderr.write("CRIT: Could not read config file: %s" % (PRINTNODE_CONFIG_PATH))
    sys.exit(3)

# Initate Log
for LOG_LEVEL_LINE in PRINTNODE_CONFIG:
    LOG_LEVEL = DEBUG_LEVEL_SWITCHER.get(LOG_LEVEL_LINE.get('LogLevel', "").lower(), 20)
    break
logging.basicConfig(level=LOG_LEVEL, filename="%s" % LOGFILE_PATH,
                    format='%(asctime)s - %(levelname)s - %(message)s')

# Get file to be printed from commandline param or stdin and encode as B64
STDIN = ""
if int(len(sys.argv)) == 7:
    FILEPATH = sys.argv[6]
    logging.debug("Reading file %s", FILEPATH)
    with open(FILEPATH, "rb") as PRINTFILE:
        FILE_B64 = base64.b64encode(bytes(PRINTFILE.read())).decode('utf-8')

    # Hack: Check if Paper is A5 (ABB-197)
    PAGESIZE = os.popen("pdfinfo %s | grep 'Page size:'" % (FILEPATH)).read()
    if "595.275 x 419.527 pts" in PAGESIZE:
        IS_A5 = True

elif int(len(sys.argv)) == 6:
    logging.debug("Reading file from stdin")
    for line in sys.stdin:
        STDIN += line
        if "595.275 419.527" in line:
            IS_A5 = True

    FILE_B64 = base64.b64encode(bytes(STDIN, encoding='utf-8')).decode('utf-8')

# Parse Config
for ACCOUNT in PRINTNODE_CONFIG:

    PRINTERS = ACCOUNT.get("Printers", "")

    # Get override Options
    OVERRIDE_OPTIONS = ACCOUNT.get("Override_Options", "")
    if OVERRIDE_OPTIONS:
        # If alternative A5 Printer is defined get override Options again
        DIFFERENT_A5_PRINTER = get_overrides(PRINTER_ID, OVERRIDE_OPTIONS)
        if DIFFERENT_A5_PRINTER and IS_A5:
            PRINTER_ID = DIFFERENT_A5_PRINTER
            get_overrides(PRINTER_ID, OVERRIDE_OPTIONS)

    # Check if printer ID is in printNode.yml
    if str(PRINTER_ID) in str(PRINTERS):
        API_KEY = ACCOUNT.get("API_Key", "")

        # Get account specific A5 Printer if no printer or queue specific printer is specfied
        if IS_A5 and "A5_Printer" in ACCOUNT and not DIFFERENT_A5_PRINTER:
            PRINTER_ID = ACCOUNT.get("A5_Printer")
            logging.debug("Setting Queue to A5 Printer: %s", PRINTER_ID)
            get_overrides(PRINTER_ID, OVERRIDE_OPTIONS)

# if printer is not in printNode.yml look it up in all accounts
if not API_KEY:
    logging.debug("Did not find ID %s in configfile %s", PRINTER_ID, PRINTNODE_CONFIG_PATH)
    PRINTER_FOUND = None
    for ACCOUNT in PRINTNODE_CONFIG:
        API_KEY = ACCOUNT.get("API_Key", "")
        if API_KEY != "" and API_KEY is not None:
            PRINTNODE_GW = Gateway(url="https://api.printnode.com", apikey="%s" % API_KEY)
            try:
                PRINTER_FOUND = PRINTNODE_GW.printers(printer=PRINTER_ID)
            except LookupError as ex:
                # Printer not found
                continue

        # Get A5 Printer
        if IS_A5 and "A5_Printer" in ACCOUNT.keys():
            PRINTER_ID = ACCOUNT.get("A5_Printer")
            logging.debug("Setting Queue to A5 Printer: %s", PRINTER_ID)

        # New Printer to config
        if PRINTER_FOUND is not None:
            WRITE_CONFIG = True
            logging.debug("Added Printer %d to configfile", PRINTER_ID)
            if ACCOUNT["Printers"] == "":
                ACCOUNT["Printers"] = "%s" % str(PRINTER_ID)
            else:
                ACCOUNT["Printers"] = "%s %s" % (ACCOUNT["Printers"], str(PRINTER_ID))
            break

    if PRINTER_FOUND is None:
        logging.critical("Printer %s not belonging to any account. "
                         "Ensure Printer_ID is valid", PRINTER_ID)
        sys.stderr.write("CRIT: Printer does not belong to any account\n")
        sys.exit(4)

# Write new config to file
if WRITE_CONFIG:
    logging.debug("Writing new printer to config file %s", PRINTNODE_CONFIG_PATH)
    with open("%s" % PRINTNODE_CONFIG_PATH, "w") as PRINTNODE_CONFIG_FILE:
        yaml.dump(PRINTNODE_CONFIG, PRINTNODE_CONFIG_FILE, default_flow_style=False,
                  sort_keys=False)

# Determine options
CUPS_OPTIONS = sys.argv[5].split(' ')
PRINTNODE_OPTIONS = {}
for VALUE in CUPS_OPTIONS:

    if VALUE[:9] == "InputSlot":
        INPUTSLOT = VALUE[10:]
        # Replace "_" with " " to enable Printnode Capabilities with spaces
        INPUTSLOT = INPUTSLOT.replace("_", " ")
        PRINTNODE_OPTIONS["bin"] = INPUTSLOT

    elif VALUE[:6] == "Duplex":
        if VALUE[7:] == "DuplexNoTumble":
            PRINTNODE_OPTIONS["duplex"] = "long-edge"
        if VALUE[7:] == "DuplexTumble":
            PRINTNODE_OPTIONS["duplex"] = "short-edge"

    elif VALUE[:10] == "ColorModel":
        if VALUE[11:].lower() == "gray":
            PRINTNODE_OPTIONS["color"] = False
        if VALUE[11:].lower() == "cymk":
            PRINTNODE_OPTIONS["color"] = True

    elif VALUE[:8] == "PageSize":
        PRINTNODE_OPTIONS["paper"] = VALUE[8:]

if PRINTNODE_OPTIONS:
    logging.debug("Options found: %s", PRINTNODE_OPTIONS)
else:
    logging.debug("No options found")

PRINTNODE_OPTIONS.update(GLOBAL_PRINTER_OVERRIDES)

if IS_A5:
    set_a5_options(A5_PRINTER_OVERRIDE_OPTIONS)

# Check if raw print
CONTENT_TYPE = os.environ["CONTENT_TYPE"]
logging.debug("Content type is %s", CONTENT_TYPE)
RAW_PRINT = CONTENT_TYPE in ("application/vnd.cups-raw", "text/plain")

# Init Gateway if it isn't already
if PRINTNODE_GW is None:
    logging.debug("Initiating PrintNode gateway")
    PRINTNODE_GW = Gateway(url='https://api.printnode.com', apikey='%s' % API_KEY)

if RAW_PRINT:
    logging.info("Initate raw print job with the following arguments: PRINTER_ID=%d title=%s",
                 PRINTER_ID, JOBTITLE)
    PRINTNODE_GW.PrintJob(printer=PRINTER_ID, job_type='raw', title='%s' % JOBTITLE,
                          base64="%s" % FILE_B64)
else:
    if PRINTNODE_OPTIONS:
        logging.info("Initate print job with the following arguments: PRINTER_ID=%d title=%s " \
                     "options=%s", PRINTER_ID, JOBTITLE, PRINTNODE_OPTIONS)
        PRINTNODE_GW.PrintJob(printer=PRINTER_ID, options=PRINTNODE_OPTIONS,
                              job_type='pdf', title='%s' % JOBTITLE, base64='%s' % FILE_B64)
    else:
        logging.info("Initate print job with the following arguments: " \
                     "PRINTER_ID=%d title=%s", PRINTER_ID, JOBTITLE)
        PRINTNODE_GW.PrintJob(printer=PRINTER_ID, job_type='pdf', title='%s' % JOBTITLE,
                              base64='%s' % FILE_B64)

logging.debug("Printjob %s finished", JOBTITLE)
